#include <stdint.h>
// 16x1024 FP32: retain row loop, explicitly unroll vectors within each row.
extern "C" __global__ [aicore] void row_softmax(__gm__ float* input, __gm__ float* output) {
    auto x = (__ubuf__ float*)get_imm(0);
    auto y = (__ubuf__ float*)get_imm(131072);
    // Batch rows 0..15.
    copy_gm_to_ubuf_align_v2((__ubuf__ uint16_t*)x, (__gm__ uint16_t*)(input + 0),
                           0, 1, 65536, 0, 0, false, 0, 0, 0);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    __VEC_SCOPE__ {
        vector_bool mask = pset_b32(PAT_ALL);
        for (uint16_t row = 0; row < 16; ++row) {
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, row * 1024 + 0, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, row * 1024 + 64, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, row * 1024 + 128, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, row * 1024 + 192, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, row * 1024 + 256, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, row * 1024 + 320, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, row * 1024 + 384, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, row * 1024 + 448, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, row * 1024 + 512, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, row * 1024 + 576, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, row * 1024 + 640, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, row * 1024 + 704, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, row * 1024 + 768, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, row * 1024 + 832, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, row * 1024 + 896, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, row * 1024 + 960, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, row * 1024 + 0, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, row * 1024 + 64, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, row * 1024 + 128, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, row * 1024 + 192, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, row * 1024 + 256, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, row * 1024 + 320, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, row * 1024 + 384, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, row * 1024 + 448, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, row * 1024 + 512, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, row * 1024 + 576, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, row * 1024 + 640, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, row * 1024 + 704, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, row * 1024 + 768, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, row * 1024 + 832, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, row * 1024 + 896, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, row * 1024 + 960, NORM_B32, mask);
        }
    }
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    copy_ubuf_to_gm_align_v2((__gm__ uint16_t*)(output + 0), (__ubuf__ uint16_t*)y,
                           0, 1, 65536, 0, 0, 0);
    pipe_barrier(PIPE_ALL);
}
