#include <stdint.h>
// 16x1024 FP32, one vector block, 1 batch(es) of 16 rows.
extern "C" __global__ [aicore] void row_softmax(__gm__ float* input, __gm__ float* output) {
    auto x = (__ubuf__ float*)get_imm(0);
    auto y = (__ubuf__ float*)get_imm(131072);
    // Rows 0..15; reuse the same UB allocation.
    copy_gm_to_ubuf_align_v2((__ubuf__ uint16_t*)x, (__gm__ uint16_t*)(input + 0),
                           0, 1, 65536, 0, 0, false, 0, 0, 0);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    __VEC_SCOPE__ {
        vector_bool mask = pset_b32(PAT_ALL);
        { // Row 0
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 0, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 64, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 128, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 192, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 256, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 320, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 384, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 448, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 512, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 576, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 640, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 704, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 768, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 832, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 896, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 960, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 0, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 64, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 128, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 192, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 256, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 320, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 384, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 448, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 512, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 576, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 640, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 704, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 768, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 832, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 896, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 960, NORM_B32, mask);
        }
        { // Row 1
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 1024, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 1088, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 1152, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 1216, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 1280, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 1344, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 1408, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 1472, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 1536, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 1600, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 1664, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 1728, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 1792, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 1856, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 1920, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 1984, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 1024, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 1088, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 1152, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 1216, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 1280, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 1344, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 1408, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 1472, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 1536, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 1600, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 1664, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 1728, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 1792, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 1856, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 1920, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 1984, NORM_B32, mask);
        }
        { // Row 2
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 2048, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 2112, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 2176, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 2240, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 2304, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 2368, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 2432, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 2496, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 2560, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 2624, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 2688, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 2752, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 2816, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 2880, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 2944, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 3008, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 2048, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 2112, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 2176, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 2240, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 2304, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 2368, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 2432, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 2496, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 2560, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 2624, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 2688, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 2752, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 2816, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 2880, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 2944, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 3008, NORM_B32, mask);
        }
        { // Row 3
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 3072, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 3136, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 3200, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 3264, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 3328, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 3392, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 3456, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 3520, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 3584, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 3648, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 3712, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 3776, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 3840, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 3904, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 3968, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 4032, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 3072, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 3136, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 3200, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 3264, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 3328, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 3392, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 3456, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 3520, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 3584, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 3648, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 3712, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 3776, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 3840, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 3904, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 3968, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 4032, NORM_B32, mask);
        }
        { // Row 4
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 4096, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 4160, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 4224, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 4288, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 4352, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 4416, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 4480, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 4544, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 4608, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 4672, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 4736, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 4800, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 4864, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 4928, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 4992, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 5056, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 4096, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 4160, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 4224, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 4288, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 4352, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 4416, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 4480, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 4544, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 4608, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 4672, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 4736, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 4800, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 4864, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 4928, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 4992, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 5056, NORM_B32, mask);
        }
        { // Row 5
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 5120, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 5184, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 5248, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 5312, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 5376, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 5440, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 5504, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 5568, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 5632, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 5696, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 5760, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 5824, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 5888, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 5952, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 6016, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 6080, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 5120, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 5184, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 5248, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 5312, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 5376, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 5440, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 5504, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 5568, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 5632, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 5696, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 5760, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 5824, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 5888, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 5952, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 6016, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 6080, NORM_B32, mask);
        }
        { // Row 6
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 6144, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 6208, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 6272, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 6336, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 6400, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 6464, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 6528, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 6592, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 6656, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 6720, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 6784, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 6848, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 6912, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 6976, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 7040, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 7104, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 6144, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 6208, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 6272, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 6336, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 6400, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 6464, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 6528, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 6592, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 6656, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 6720, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 6784, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 6848, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 6912, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 6976, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 7040, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 7104, NORM_B32, mask);
        }
        { // Row 7
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 7168, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 7232, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 7296, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 7360, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 7424, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 7488, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 7552, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 7616, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 7680, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 7744, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 7808, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 7872, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 7936, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 8000, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 8064, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 8128, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 7168, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 7232, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 7296, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 7360, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 7424, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 7488, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 7552, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 7616, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 7680, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 7744, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 7808, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 7872, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 7936, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 8000, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 8064, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 8128, NORM_B32, mask);
        }
        { // Row 8
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 8192, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 8256, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 8320, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 8384, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 8448, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 8512, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 8576, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 8640, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 8704, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 8768, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 8832, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 8896, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 8960, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 9024, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 9088, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 9152, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 8192, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 8256, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 8320, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 8384, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 8448, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 8512, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 8576, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 8640, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 8704, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 8768, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 8832, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 8896, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 8960, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 9024, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 9088, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 9152, NORM_B32, mask);
        }
        { // Row 9
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 9216, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 9280, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 9344, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 9408, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 9472, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 9536, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 9600, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 9664, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 9728, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 9792, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 9856, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 9920, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 9984, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 10048, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 10112, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 10176, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 9216, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 9280, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 9344, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 9408, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 9472, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 9536, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 9600, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 9664, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 9728, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 9792, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 9856, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 9920, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 9984, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 10048, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 10112, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 10176, NORM_B32, mask);
        }
        { // Row 10
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 10240, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 10304, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 10368, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 10432, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 10496, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 10560, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 10624, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 10688, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 10752, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 10816, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 10880, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 10944, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 11008, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 11072, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 11136, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 11200, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 10240, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 10304, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 10368, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 10432, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 10496, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 10560, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 10624, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 10688, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 10752, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 10816, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 10880, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 10944, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 11008, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 11072, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 11136, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 11200, NORM_B32, mask);
        }
        { // Row 11
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 11264, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 11328, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 11392, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 11456, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 11520, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 11584, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 11648, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 11712, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 11776, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 11840, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 11904, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 11968, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 12032, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 12096, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 12160, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 12224, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 11264, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 11328, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 11392, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 11456, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 11520, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 11584, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 11648, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 11712, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 11776, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 11840, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 11904, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 11968, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 12032, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 12096, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 12160, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 12224, NORM_B32, mask);
        }
        { // Row 12
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 12288, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 12352, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 12416, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 12480, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 12544, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 12608, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 12672, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 12736, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 12800, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 12864, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 12928, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 12992, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 13056, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 13120, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 13184, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 13248, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 12288, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 12352, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 12416, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 12480, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 12544, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 12608, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 12672, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 12736, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 12800, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 12864, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 12928, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 12992, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 13056, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 13120, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 13184, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 13248, NORM_B32, mask);
        }
        { // Row 13
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 13312, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 13376, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 13440, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 13504, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 13568, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 13632, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 13696, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 13760, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 13824, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 13888, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 13952, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 14016, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 14080, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 14144, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 14208, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 14272, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 13312, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 13376, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 13440, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 13504, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 13568, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 13632, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 13696, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 13760, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 13824, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 13888, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 13952, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 14016, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 14080, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 14144, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 14208, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 14272, NORM_B32, mask);
        }
        { // Row 14
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 14336, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 14400, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 14464, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 14528, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 14592, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 14656, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 14720, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 14784, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 14848, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 14912, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 14976, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 15040, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 15104, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 15168, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 15232, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 15296, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 14336, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 14400, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 14464, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 14528, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 14592, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 14656, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 14720, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 14784, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 14848, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 14912, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 14976, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 15040, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 15104, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 15168, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 15232, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 15296, NORM_B32, mask);
        }
        { // Row 15
            vector_f32 v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15;
            vector_f32 maxv, reduced, rowmax, sums, rowsum;
            vdup(maxv, -3.402823466e38f, mask, MODE_ZEROING);
            vlds(v0, x, 15360, NORM);
            vmax(maxv, maxv, v0, mask, MODE_ZEROING);
            vlds(v1, x, 15424, NORM);
            vmax(maxv, maxv, v1, mask, MODE_ZEROING);
            vlds(v2, x, 15488, NORM);
            vmax(maxv, maxv, v2, mask, MODE_ZEROING);
            vlds(v3, x, 15552, NORM);
            vmax(maxv, maxv, v3, mask, MODE_ZEROING);
            vlds(v4, x, 15616, NORM);
            vmax(maxv, maxv, v4, mask, MODE_ZEROING);
            vlds(v5, x, 15680, NORM);
            vmax(maxv, maxv, v5, mask, MODE_ZEROING);
            vlds(v6, x, 15744, NORM);
            vmax(maxv, maxv, v6, mask, MODE_ZEROING);
            vlds(v7, x, 15808, NORM);
            vmax(maxv, maxv, v7, mask, MODE_ZEROING);
            vlds(v8, x, 15872, NORM);
            vmax(maxv, maxv, v8, mask, MODE_ZEROING);
            vlds(v9, x, 15936, NORM);
            vmax(maxv, maxv, v9, mask, MODE_ZEROING);
            vlds(v10, x, 16000, NORM);
            vmax(maxv, maxv, v10, mask, MODE_ZEROING);
            vlds(v11, x, 16064, NORM);
            vmax(maxv, maxv, v11, mask, MODE_ZEROING);
            vlds(v12, x, 16128, NORM);
            vmax(maxv, maxv, v12, mask, MODE_ZEROING);
            vlds(v13, x, 16192, NORM);
            vmax(maxv, maxv, v13, mask, MODE_ZEROING);
            vlds(v14, x, 16256, NORM);
            vmax(maxv, maxv, v14, mask, MODE_ZEROING);
            vlds(v15, x, 16320, NORM);
            vmax(maxv, maxv, v15, mask, MODE_ZEROING);
            vcmax(reduced, maxv, mask, MODE_ZEROING);
            vdup(rowmax, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdup(sums, 0.0f, mask, MODE_ZEROING);
            vsub(v0, v0, rowmax, mask, MODE_ZEROING);
            vexp(v0, v0, mask, MODE_ZEROING);
            vadd(sums, sums, v0, mask, MODE_ZEROING);
            vsub(v1, v1, rowmax, mask, MODE_ZEROING);
            vexp(v1, v1, mask, MODE_ZEROING);
            vadd(sums, sums, v1, mask, MODE_ZEROING);
            vsub(v2, v2, rowmax, mask, MODE_ZEROING);
            vexp(v2, v2, mask, MODE_ZEROING);
            vadd(sums, sums, v2, mask, MODE_ZEROING);
            vsub(v3, v3, rowmax, mask, MODE_ZEROING);
            vexp(v3, v3, mask, MODE_ZEROING);
            vadd(sums, sums, v3, mask, MODE_ZEROING);
            vsub(v4, v4, rowmax, mask, MODE_ZEROING);
            vexp(v4, v4, mask, MODE_ZEROING);
            vadd(sums, sums, v4, mask, MODE_ZEROING);
            vsub(v5, v5, rowmax, mask, MODE_ZEROING);
            vexp(v5, v5, mask, MODE_ZEROING);
            vadd(sums, sums, v5, mask, MODE_ZEROING);
            vsub(v6, v6, rowmax, mask, MODE_ZEROING);
            vexp(v6, v6, mask, MODE_ZEROING);
            vadd(sums, sums, v6, mask, MODE_ZEROING);
            vsub(v7, v7, rowmax, mask, MODE_ZEROING);
            vexp(v7, v7, mask, MODE_ZEROING);
            vadd(sums, sums, v7, mask, MODE_ZEROING);
            vsub(v8, v8, rowmax, mask, MODE_ZEROING);
            vexp(v8, v8, mask, MODE_ZEROING);
            vadd(sums, sums, v8, mask, MODE_ZEROING);
            vsub(v9, v9, rowmax, mask, MODE_ZEROING);
            vexp(v9, v9, mask, MODE_ZEROING);
            vadd(sums, sums, v9, mask, MODE_ZEROING);
            vsub(v10, v10, rowmax, mask, MODE_ZEROING);
            vexp(v10, v10, mask, MODE_ZEROING);
            vadd(sums, sums, v10, mask, MODE_ZEROING);
            vsub(v11, v11, rowmax, mask, MODE_ZEROING);
            vexp(v11, v11, mask, MODE_ZEROING);
            vadd(sums, sums, v11, mask, MODE_ZEROING);
            vsub(v12, v12, rowmax, mask, MODE_ZEROING);
            vexp(v12, v12, mask, MODE_ZEROING);
            vadd(sums, sums, v12, mask, MODE_ZEROING);
            vsub(v13, v13, rowmax, mask, MODE_ZEROING);
            vexp(v13, v13, mask, MODE_ZEROING);
            vadd(sums, sums, v13, mask, MODE_ZEROING);
            vsub(v14, v14, rowmax, mask, MODE_ZEROING);
            vexp(v14, v14, mask, MODE_ZEROING);
            vadd(sums, sums, v14, mask, MODE_ZEROING);
            vsub(v15, v15, rowmax, mask, MODE_ZEROING);
            vexp(v15, v15, mask, MODE_ZEROING);
            vadd(sums, sums, v15, mask, MODE_ZEROING);
            vcadd(reduced, sums, mask, MODE_ZEROING);
            vdup(rowsum, reduced, mask, POS_LOWEST, MODE_ZEROING);
            vdiv(v0, v0, rowsum, mask, MODE_ZEROING);
            vsts(v0, y, 15360, NORM_B32, mask);
            vdiv(v1, v1, rowsum, mask, MODE_ZEROING);
            vsts(v1, y, 15424, NORM_B32, mask);
            vdiv(v2, v2, rowsum, mask, MODE_ZEROING);
            vsts(v2, y, 15488, NORM_B32, mask);
            vdiv(v3, v3, rowsum, mask, MODE_ZEROING);
            vsts(v3, y, 15552, NORM_B32, mask);
            vdiv(v4, v4, rowsum, mask, MODE_ZEROING);
            vsts(v4, y, 15616, NORM_B32, mask);
            vdiv(v5, v5, rowsum, mask, MODE_ZEROING);
            vsts(v5, y, 15680, NORM_B32, mask);
            vdiv(v6, v6, rowsum, mask, MODE_ZEROING);
            vsts(v6, y, 15744, NORM_B32, mask);
            vdiv(v7, v7, rowsum, mask, MODE_ZEROING);
            vsts(v7, y, 15808, NORM_B32, mask);
            vdiv(v8, v8, rowsum, mask, MODE_ZEROING);
            vsts(v8, y, 15872, NORM_B32, mask);
            vdiv(v9, v9, rowsum, mask, MODE_ZEROING);
            vsts(v9, y, 15936, NORM_B32, mask);
            vdiv(v10, v10, rowsum, mask, MODE_ZEROING);
            vsts(v10, y, 16000, NORM_B32, mask);
            vdiv(v11, v11, rowsum, mask, MODE_ZEROING);
            vsts(v11, y, 16064, NORM_B32, mask);
            vdiv(v12, v12, rowsum, mask, MODE_ZEROING);
            vsts(v12, y, 16128, NORM_B32, mask);
            vdiv(v13, v13, rowsum, mask, MODE_ZEROING);
            vsts(v13, y, 16192, NORM_B32, mask);
            vdiv(v14, v14, rowsum, mask, MODE_ZEROING);
            vsts(v14, y, 16256, NORM_B32, mask);
            vdiv(v15, v15, rowsum, mask, MODE_ZEROING);
            vsts(v15, y, 16320, NORM_B32, mask);
        }
    }
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    copy_ubuf_to_gm_align_v2((__gm__ uint16_t*)(output + 0), (__ubuf__ uint16_t*)y,
                           0, 1, 65536, 0, 0, 0);
    pipe_barrier(PIPE_ALL);
}
